### ISSUE TITLE
Node.js 16 is deprecated

### ISSUE THREAD

**Issue by sinsukehlab** [dduzgun-security/secure-code-game-action#5]
### Summary

Node.js 16 is deprecated.

### Content

This action uses Node.js 16, which is now deprecated. In [skills/secure-code-game](/skills/secure-code-game), the workflow that uses the action raises warning.
Is this deprecated version usage is deliberate or should the version be updated?

### Discussed in https://github.com/skills/secure-code-game/discussions/87#discussioncomment-9048923

<div type='discussions-op-text'>

<sup>Originally posted by **sinsukehlab** April  9, 2024</sup>
Yes, I refer to Season 2 Level 1.
The action [dduzgun-security/secure-code-game-action](/dduzgun-security/secure-code-game-action) used in the workflow jarvis-code.yml still uses Node.js 16.
https://github.com/dduzgun-security/secure-code-game-action/blob/b30b00ac91e4cbd0a8636ccbef1f38f4ffc376ea/action.yml#L16-L18
```yml
runs:
  using: 'node16'
  main: 'index.js'
```
</div>

**Comment by dduzgun-security** [comment]
👋 @sinsukehlab thanks for opening an issue, I think we should update the version. Would you be open to contribute by submitting a PR?

**Comment by sinsukehlab** [comment]
Sure, I will open a PR later.

**Comment by sinsukehlab** [comment]
Also, this repository doesn't have a .gitignore file. I would also like to add .gitignore (Node template) in my PR. This might not affect the course because ~the deliberate vulnerability is introduced in package.json and package-lock.json as far as I know~.
Oh, there's no deliberate vulnerability in this repo itself. The jarvis-hack.yml workflow file simply monitors push to the jarvis-code.yml workflow file.

**Comment by jkcso** [comment]
@sinsukehlab for now please include only the Node update as there's a .gitignore file on the repository level. If you want to update the .gitignore, let's do this separately please.

**Comment by sinsukehlab** [comment]
@jkcso All right, I will open PRs separately. I would like to clarify what you meant by "on the repository level". There is no .gitignore file in this repository.

**Comment by jkcso** [comment]
@sinsukehlab you are correct! I didn't realize I was inside this repo, I was thinking about the Secure Code Game repo :-)

**Comment by dduzgun-security** [comment]
Please feel free to also include a `.gitignore` in the PR 🙏 
[This](https://github.com/github/gitignore/blob/main/Node.gitignore) could be good, however I think we may maybe need to keep the `node_modules` for the action to work?

**Comment by sinsukehlab** [comment]
@dduzgun-security All right, I will open a PR that bumps the Node.js version and adds a .gitignore file.
I think you can include `node_modules/` in the .gitignore file of an action repo using Node.js.
See: https://github.com/actions/setup-node/blob/main/.gitignore
